### ISSUE TITLE
Illustration link in README points to a non-existent file

### ISSUE THREAD

**Issue by ctb** [KatyBrown/plot_phylo#1]
in https://github.com/KatyBrown/plot_phylo/blob/main/README.md, the first link to an illustration points to https://github.com/KatyBrown/plot_phylo/blob/main/examples/layered.png, which does not exist.

Once that's fixed, you could also use Markdown image inclusion: `![layered image description](link to layered.png)` to include it inline in the README.

**Comment by KatyBrown** [comment]
Fixed in https://github.com/KatyBrown/plot_phylo/commit/2b3c0c26857596fb7aed75f56b457ac43ac5829a - thank you!
