### ISSUE TITLE
GitHub link in documentation may only be for people with github accounts.

### ISSUE THREAD

**Issue by ctb** [KatyBrown/plot_phylo#2]
Looking at https://plot-phylo.readthedocs.io/en/latest/pages/installation.html (and also the README), I see
```
git clone git@github.com:KatyBrown/plot_phylo.git
```
I can clone it from there, but I have a github ssh key - when I disable my ssh key, it denies me login permission.

I suspect the right URL to provide for truly read-only access by people from anywhere would be the HTTPS URL:

https://github.com/KatyBrown/plot_phylo.git

**Comment by KatyBrown** [comment]
Ah I didn't know there was a difference! I'll fix it.

**Comment by KatyBrown** [comment]
Addressed in https://github.com/KatyBrown/plot_phylo/commit/4947f3364bd4d73726451b6a8d0bd28f7d851c72
