### ISSUE TITLE
the detailed example is not quite complete

### ISSUE THREAD

**Issue by ctb** [KatyBrown/plot_phylo#3]
the example here, https://plot-phylo.readthedocs.io/en/latest/pages/detailed.html, needs two import statements at the top:

```
import plot_phylo
import matplotlib.pyplot as plt
```

It also seems to suffer from cwd-confusion - it both needs to be run in the presence of several newick files in the `examples/` subdirectory (implying that cwd should be `examples`) and outputs to `examples/layered.png`, implying that it should be in the root directory.

Once those things are adjusted, it works great!

(I think it would be nice to indicate at the top of the example exactly where it should be run, and what files it needs in order to run - it took me about a minute to get it working, which is a loooong time in example-land! :)

My version attached.

[tst.py.zip](https://github.com/KatyBrown/plot_phylo/files/15181313/tst.py.zip)

**Comment by ctb** [comment]
on the plus side I now have a `layered.png` ref https://github.com/KatyBrown/plot_phylo/issues/1 😆

**Comment by KatyBrown** [comment]
Thanks! I'll sort it out asap.

**Comment by KatyBrown** [comment]
Addressed in https://github.com/KatyBrown/plot_phylo/commit/0490e843a50a7d18486c72d427242b586e104deb
